# refer https://github.com/HexmosTech/glee#configuration for configuration details

[ghost-configuration]

ADMIN_API_KEY = ""   # eg: 5c5d4dfce3q:1ec32we4d5w7cq refer: https://ghost.org/docs/admin-api/#permissions

GHOST_VERSION = "v5" # eg: v5,v4... refer: https://github.com/HexmosTech/glee#ghost-version

GHOST_URL = ""       # eg: https://ghost-hosted-url/ghost

[blog-configuration] # global configuration for all blog posts

SIDEBAR_TOC = false  # enable/disable right sidebar in blogs.
FEATURED = false     # enable/disable feature this post option.
STATUS = "draft"     # options: "draft" or "published"
CODE_HILITE_THEME = "monokai" #other options: native, pastie, vim, fruity

[image-configuration]

IMAGE_BACKEND = "ghost"  #options: "ghost" or "s3"

[video-configuration]

VIDEO_BACKEND = "s3"  #options: "ghost" or "s3"

[aws-s3-configuration]   #optional; Fill in if you are using "s3" as the IMAGE_BACKEND : refer: https://docs.aws.amazon.com/AmazonS3/latest/userguide/create-bucket-overview.html

ACCESS_KEY_ID = ""       # eg: UZNN442KVSB7AQTOIAW2 refer: https://objectivefs.com/howto/how-to-get-amazon-s3-keys

SECRET_ACCESS_KEY = ""   # eg: 2gP5NeQ2KLkcKLkcPyRqhmzY3WSK2I+GmI/T4qQ255 refer:https://objectivefs.com/howto/how-to-get-amazon-s3-keys

BUCKET_NAME = ""

REGION = ""