# refer https://github.com/HexmosTech/glee#configuration for configuration details

[ghost-configuration]
ADMIN_API_KEY = "" 
GHOST_VERSION = ""  # eg: v5,v4...
GHOST_URL =""

[aws-s3-configuration]
ACCESS_KEY_ID = ""
SECRET_ACCESS_KEY = ""
BUCKET = ""
S3_BASE_URL = ""