[ghost-configuration]
ADMIN_API_KEY = "335e3dde34354:53434feddd3r3dd"

GHOST_VERSION = "v5"  # eg: v5,v4...
GHOST_URL ="https://example.com/ghost"

[aws-s3-configuration]
ACCESS_KEY_ID = "ABCDEFJDERJRJR"
SECRET_ACCESS_KEY = "ABCDSWSWSAQEFJDERJRJRDWSWSWW"
BUCKET = "sample bucket"
S3_BASE_URL = "https://example.s3.ap-south-1.amazonaws.com/"