name: glee 
on: [push]



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
      - name: Install dependencies
        run: |
          cd glee-go
          go mod tidy
      - name: Build
        run: | 
          cd glee-go
          go build -v ./...
      - name: Test with the Go CLI
        run: |
          cd glee-go
          go mod tidy
          go build -o build/l2 -ldflags "-X main.version=`git tag --sort=-version:refname | head -n 1`" glee.go
